import { Inter } from "next/font/google";
import "./globals.css";
import SettingProvider from "@/context/SettingContext";
import MenuProvider from "@/context/MenuContext";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Boda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SettingProvider>
          <MenuProvider>{children}</MenuProvider>
        </SettingProvider>
      </body>
    </html>
  );
}
